version: "3"
services:
  proxy:
    image: nginx:1.27-alpine3.20
    restart: unless-stopped
    depends_on:
      - app
      - index
      - store
    networks:
      - public
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  app:
    build: ./app
    restart: unless-stopped
    networks:
      - public

  index:
    image: postgres:15.8
    restart: unless-stopped
    networks:
      - private
    volumes:
      - index:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  store:
    image: orthancteam/orthanc:24.10.1
    restart: unless-stopped
    depends_on:
      - index
    networks:
      - public
      - private
    volumes:
      - store:/var/lib/orthanc/db
      - ./store/configuration.json:/etc/orthanc/configuration.json

volumes:
  index:
  store:

networks:
  public:
  private:
