services:
  surrogate:
    extends:
      file: common-services.yml
      service: surrogate

  broker:
    image: broker
    command: gunicorn -b 0.0.0.0:3000 --chdir /usr/local/src/broker/src --reload app:app
    extends:
      file: common-services.yml
      service: broker

  viewer:
    image: viewer
    command: yarn --cwd /usr/local/src/viewer run dev
    extends:
      file: common-services.yml
      service: viewer
    ports:
      - 3000:3000

  postgresql:
    extends:
      file: common-services.yml
      service: postgresql

  orthanc:
    extends:
      file: common-services.yml
      service: orthanc


volumes:
  index:
  store:

networks:
  public:
  private: