services:
  app:
    image: app
    build: ./app
    environment:
      APP_COMMIT: "43f54aa49c388dbeb2f01e19244210a4f3bda6c5"
  proxy:
    image: proxy
    build: ./proxy
    ports: ["80:80", "443:443"]