services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./build/app.dockerfile
  proxy:
    image: proxy
    build:
      context: .
      dockerfile: ./build/proxy.dockerfile
    ports: ["80:80", "443:443"]