version: "3"
services:
  proxy:
    build: ./proxy
    depends_on: [app, index, store]
    restart: unless-stopped
    ports: ["80:80", "443:443"]

  app:
    build: ./app
    restart: unless-stopped
    environment:
      APP_COMMIT: "43f54aa49c388dbeb2f01e19244210a4f3bda6c5"

  index:
    image: postgres:15.8
    restart: unless-stopped
    volumes: ["index:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  store:
    build: ./store
    depends_on: [index]
    restart: unless-stopped
    volumes: ["store:/var/lib/orthanc/db"]

volumes:
  index:
  store: